name: Deploy demo benchmark
on: 
  push:
    branches:
      - "main"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
       version: latest
       run_install: false
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: latest
        cache: pnpm
    - name: Install packages
      run: pnpm i
    - name: Build benchmark
      run: pnpm build
    - name: Deploy with gh-pages
      run: |
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        pnpm run deploy -- -u "github-actions-bot <support+actions@github.com>"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

